# Generated by Django 3.2.9 on 2023-02-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0002_signup_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='signup',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
