# Generated by Django 3.2.9 on 2023-02-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0004_alter_signup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
