# Generated by Django 3.2.9 on 2023-02-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0005_alter_signup_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='graduation_semester_1',
            new_name='graduation_semester_1_CGPA_or_percentage',
        ),
        migrations.RenameField(
            model_name='studentdata',
            old_name='graduation_semester_2',
            new_name='graduation_semester_2_CGPA_or_percentage',
        ),
        migrations.RenameField(
            model_name='studentdata',
            old_name='graduation_semester_3',
            new_name='graduation_semester_3_CGPA_or_percentage',
        ),
        migrations.RenameField(
            model_name='studentdata',
            old_name='graduation_semester_4',
            new_name='graduation_semester_4_CGPA_or_percentage',
        ),
        migrations.RenameField(
            model_name='studentdata',
            old_name='graduation_semester_5',
            new_name='graduation_semester_5_CGPA_or_percentage',
        ),
        migrations.RenameField(
            model_name='studentdata',
            old_name='graduation_semester_6',
            new_name='graduation_semester_6_CGPA_or_percentage',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='overall_CGPA_or_percentage',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='upload_cv',
            field=models.FileField(blank=True, null=True, upload_to='CV'),
        ),
    ]
